test
Hansung-include/dataStructure pull request #2
Opened 2023-03-25 04:24 UTC by zlzla

2023-03-25 05:45 UTC, JeeIn-Shin requested changes
파일 내용이 아무것도 없습니다. 재제출 부탁드립니다.

2023-03-26 07:17 UTC, wrg2674 approved these changes
객체가 있는 언어의 경우는 자료구조를 공부하는데 추상화도 나오는 군요.

2023-03-26 14:07 UTC, JeeIn-Shin approved these changes

2023-03-26 14:11 UTC, JeeIn-Shin commented
스터디 하신다고 고생 많으셨습니다. 파이썬에 대해 몰라서 여쭤보고싶은게 있습니다.
1) 그럼 파이썬의 경우는 i = 0, temp = "str" 이런 식으로 변수만 선언하나요? 
2) 내부적으로 어떻게 구현했는지 감춰져있다가 정확하게 무슨 말인가요? 모듈의 소스코드를 확인할 수 없다는 의민가요?

2023-03-26 16:51 UTC, zlzla commented
> 스터디 하신다고 고생 많으셨습니다. 파이썬에 대해 몰라서 여쭤보고싶은게 있습니다.
> 
> 1. 그럼 파이썬의 경우는 i = 0, temp = "str" 이런 식으로 변수만 선언하나요?


> 2. 내부적으로 어떻게 구현했는지 감춰져있다가 정확하게 무슨 말인가요? 모듈의 소스코드를 확인할 수 없다는 의민가요?

2023-03-27 02:42 UTC, zlzla commented
.

2023-03-27 04:55 UTC, zlzla commented
좋은 질문 감사합니다. 제가 파이썬에 대해서 모르게 많지만, 답변드리겠습니다. 틀린부분이 있으면 지적해주시길 바랍니다.

> 1. 그럼 파이썬의 경우는 i = 0, temp = "str" 이런 식으로 변수만 선언하나요?

네, 파이썬에서는 변수 선언 및 초기화를 할때는 
단순히 i = 0이라고 쓰면됩니다. 

파이썬에서는 직접 자료형을 지정하지않아도 내부적으로 알아서 데이터에 따라 데이터 타입을 설정해줍니다.




> 2. 내부적으로 어떻게 구현했는지 감춰져있다가 정확하게 무슨 말인가요? 모듈의 소스코드를 확인할 수 없다는 의민가요?

'내부적으로 어떻게 구현했는지 감춰져있다'라는 말은
 사용자가 파이썬에서 함수를 사용할때 그 원리는 C언어로만든 파이썬안에 있어서 감추어져있다고 표현했습니다.

파이썬 내부구조를 살펴보면 어떻게 구현되는지 알수있지않을까 싶습니다. 모듈의 소스코드를 확인할 수 있는지는 찾지못했습니다.


https://leemoney93.tistory.com/25
위 블로그는 파이썬이 메모리관리하는방법에대한 내용인데

파이썬에서 a = 2라는 코드를 짜면

우리는 단순히  변수 a에 2라는 값을 저장해있다 생각하지만


파이썬안에서는

2라는 숫자를 개체로 보고 

이 개체가 int형인지, 참조하는 변수가 몇갠지 알수있도록 프로그래밍되어있습니다.
이렇기때문에 파이썬안에서 내부적으로 a라는 변수를 어떤 형식으로 인식하도록 프로그래밍 되어있고 이 과정이 감추어져있다고 표현한겁니다.

2023-03-27 06:26 UTC, JeeIn-Shin commented
오호,, 파이썬이 C로 만들어졌군요? 모듈의 소스코드 자체가 감춰져있다는 의민줄 알았는데 이런 의미였군요 감사합니다.
되게 재밌네요.  그럼 조금 더 궁금한게 있습니다.

i;
j = 3;
이런 식으로 변수를 선언할 수 있나요? 이런 경우
i += j;
라고 한다면 i의 값은 어떻게 되나요? js랑 비슷한 듯 다른게 많아서 궁금해졌습니다.

js의 경우는 아래와 같은 결과를 출력합니다.
![image](https://user-images.githubusercontent.com/58104623/227857944-9d7ba44c-1d0b-4530-b8eb-f4af85e0627d.png)

2023-03-27 06:57 UTC, zlzla commented
파이썬과 자바스크립트이 비슷한 점이 보이는 이유는 둘다 동적 타입언어이기때문입니다.


![image](https://user-images.githubusercontent.com/127752188/227863534-9d387bcc-49d1-495b-ae58-03b384bee311.png)

파이썬에서 i는 None타입으로 인식하고 j는 int형으로 자동으로 설정해줍니다. 
둘의 연산은 자료형이 안맞기 때문에 수행되지않습니다.


[CS] 정적타입 언어 vs 동적타입 언어
https://velog.io/@eunnbi/%EC%A0%95%EC%A0%81%ED%83%80%EC%9E%85-%EC%96%B8%EC%96%B4-vs-%EB%8F%99%EC%A0%81%ED%83%80%EC%9E%85-%EC%96%B8%EC%96%B4

2023-03-27 07:02 UTC, JeeIn-Shin commented
앗 파이썬은 무조건 그럼 변수 선언과 함께 초기화를 해줘야하는군요? 덕분에 궁금증이 해결됐습니다 감사합니다.

2023-03-27 11:05 UTC, mj0107 approved these changes

2023-03-29 13:58 UTC, MJW207 approved these changes

2023-03-29 14:32 UTC, mmije0ng approved these changes

2023-04-01 05:35 UTC, merged